### ISSUE TITLE
User Manual: Add information of needed Bautrate

### ISSUE THREAD

**Issue by mikelovic** [Open-Lab-Starter-Kit/OLSK-Small-Laser#1]
Hey,

one proposal to add the value of needed Baud Rate for the connection of UGS with the Lasercutter.
Ref -> Manuel ->  https://github.com/Open-Lab-Starter-Kit/OLSK-Small-Laser/blob/main/manual/OLSK_Small_Laser_V1_User%20manual_L1M1.pdf

On page 12, there is the info of "select here the port and baud" and infotext for step3 with "In the upper bar, select the correct Port and Baud."
I assume the Baudrate is fixed in the tinsy control unit, so the info of the needed Baudrate would be helpful here. You see it in the screenshot (Baudrate = 115200) but in low resolution.

Cheers

**Comment by licash** [comment]
Solved. Baudrate added to User Manual.
